// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA3JQJ5bvfxXTW6-8DkXGiCBNBtwnFvuA',
    appId: '1:146575206726:web:5a5734a93a84ba5e6c5d47',
    messagingSenderId: '146575206726',
    projectId: 'ganttchart-9b288',
    authDomain: 'ganttchart-9b288.firebaseapp.com',
    storageBucket: 'ganttchart-9b288.firebasestorage.app',
    measurementId: 'G-Z8BRLJ7DG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-p6M38rjGpCPHzHkAJ5AJ4PivJqTaKA',
    appId: '1:146575206726:android:d7836d26e24f15026c5d47',
    messagingSenderId: '146575206726',
    projectId: 'ganttchart-9b288',
    storageBucket: 'ganttchart-9b288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvPF_28DfleDv_Z2DIe4p-Pv0NbY7da0',
    appId: '1:146575206726:ios:2f9146742b9a89f86c5d47',
    messagingSenderId: '146575206726',
    projectId: 'ganttchart-9b288',
    storageBucket: 'ganttchart-9b288.firebasestorage.app',
    iosBundleId: 'jp.yoshiyuki.ganttchart01',
  );
}
